// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:  "postgresql://neondb_owner:npg_gTHFcA3npU8s@ep-damp-mouse-adm04q4r.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&connect_timeout=15"
  },
});
